Allow running in docker
GothenburgBitFactory/taskserver pull request #151
Opened 2018-10-11 12:29 UTC by techhazard

I wanted to be able to run taskwarrior in docker. There was no `Dockerfile` that I could find, so I made one.

The final image is around 100MB in size. 
I was unable to statically compile/link (my gcc-fu isn't good enough :-p). If that's possible, we can reduce probably return it to under 10MB, especially if it can be linked with musl-libc.

The image can be run with the following:
```sh
docker build -t taskserver .
docker run --rm --name taskserver -p 53589:53589 taskserver
```
Taskserver should now be available on port `53589`

I hope you like it :slightly_smiling_face:

2019-06-01 00:42 UTC, jrabbit requested changes
Seems ok we need this rebased or we'd need to cherry-pick it

2019-06-01 00:42 UTC, jrabbit commented on Dockerfile
> +RUN make -j3
This shouldn't be hardcoded

2019-06-01 00:42 UTC, jrabbit commented on Dockerfile
> +COPY ./cmake /build/cmake
Could we just copy the whole source tree?

2020-11-21 14:42 UTC, pbeckingham commented
350 commits on master? We don't work on master, please resubmit as PR on the latest development branch.

2023-01-25 21:10 UTC, hickey commented
For anyone following this PR, I have produced a Docker container for `taskd`. This work was done due to the shutdown of Freecinc and I figured that there would be others looking to bring up their own taskservers to sync between multiple machines. The container weights in just under 20MB. Project is over at https://gitlab.com/wt0f/taskd/

2023-02-07 08:28 UTC, closed without merging